### ISSUE TITLE
About the messy code

### ISSUE THREAD

**Issue by DViridescent** [xiaofanlin/NumGuess#1]
When I click 「open this file in github for windows」 I find that the Chinese character became[ ��]. I wonder how to solve this problem.
(I tried to upload a screenshot, but I failed.)

I notice that you use the head file string.h. Then I find that you have judged the player's input, which is what I don't take into account and great.

**Comment by ghost** [comment]
Your code is simple but powerful.That'great!

**Comment by xiaofanlin** [comment]
Thank you! You download the program to see the code then it won't be like this.
